---
title: "Seminario tema 5"
author: 
  - "María Acevedo Fernández"
  - "Carmen Albillos Gubia"
enlace a github [https://github.com/maf1013/Practica5]
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Repositorio GitHub: https://github.com/maf1013/Practica5.git 

## Introducción
Repositorio creado y desarrollado por alumnas del grupo 102 de la asignatura "Fuentes de Datos Biomédicas y Web Semántica" del grado Ingeniería de la Salud, Universidad de Burgos.

En este proyecto se estudia la posible relación entre la cantidad de fosfatos en ríos y el cáncer de estómago. Para ello se ha recogido información sobre los mg de PO04 por litro en los ríos de Europa (2000-2021) y el número de casos de cáncer de estómago en Europa (2005-2013). 


## Objetivos y preguntas
#### 1. La evolución del fosfato en rios (Comparando la toma de datos del primer año con el último.) 
Debido a la regulación de productos químicos y detergentes, la mejora en el tratamiento de aguas residuales, las prácticas agrícolas sostenibles y la directiva del marco de la UE se nota un descenso general en los niveles de fosfato de los ríos de Europa desde el año 2000 al año 2021.
El promedio de niveles de fosfato de todos los ríos de Europa en el año 2000 es de 0,102672727 y en el año 2021 es de 0,066486364. Sin embargo, hay países que no cumplen esta regla como es el caso de España, en el año 2000 la concentración de fosfato en ríos era de 0,113 y el 2021 de 0,199.

#### 2. País en Europa con más fosfato en ríos
En los años 2000, 2002, 2003, 2004 y 2012, Serbia registró los niveles más altos de fosfato en sus ríos, mientras que en el resto de los años fue el Norte de Macedonia quien reportó los peores datos. Al comparar estos niveles con los de países como Noruega, la diferencia es notable: por ejemplo, en el año 2000, el Norte de Macedonia alcanzó 0,4731 mg de PO₄ por litro, mientras que Noruega registró solo 0,004 mg de PO₄/L.

Esta diferencia se debe a que países más desarrollados, como Noruega y Finlandia, tienen un PIB per cápita mucho más alto, lo que les permite invertir en sistemas avanzados de agua y saneamiento. Estos sistemas están altamente desarrollados y son muy eficientes en el tratamiento de aguas residuales, reduciendo significativamente los niveles de fosfato en sus ríos.

#### 3. ¿El cancer de estómago se ve influenciado por el sexo de los pacientes?
Podemos concluir que los hombres tienen un mayor predisposición a sufrir cáncer de estómago que las mujeres. Podemos tomar varios países de ejemplo para observar esta relación calculando el promedio de los datos de todos los años presentes:
  - En Austria (AT) los hombres tienen una incidencia de 25,53, sin embargo las mujeres tienen una incidencia de 13,51
  - En Dinamarca (DK) los hombres tienen una incidencia de 16,44, sin embargo las mujeres tienen una incidencia de 6,95
  En ambos paises podemos observar como el riesgo a cancer de estómago en el sexo masculino es aproximadamente el doble que en el sexo femenino.
  
Esto se debe a varios factores:
  - Factores hormonales: El estrógeno es una hormona femenina que tiene un efecto protector contar el cáncer gástrico, por lo que las mujeres premenopúsicas son las que menos riesgo tienen de sufrirlo, ya que son las personas con niveles más altos de esta hormona
  - Infección por Helicobacter Pylori: esta bacteria es una de las causas principales de cáncer de estómago. Y aunque la tasa de infección es similar para ambos sexos, el desarrollo de cáncer a partri de esta infección es más común en los hombres.
  - Estilo de vida: según las estadísticas los hombres tienden a un mayor consumo de tabaco y alcohol, factores de riesgo para el desarrollo de cáncer de estómago.

Además podemos destacar que otro factor que afecta considerablemente en el desarrollo de este cáncer es la edad, que afecta a ambos sexos.

#### 4. ¿En los paises europeos más desarrollados y con mejor economía hay una menor tasa de cáncer de estómago?
Según el Índice de Desarrollo Humano (IDH), los países más desarrollados en Europa son:
- Noruega: 13.072
- Suiza: 11.68

Sin embargo, entre los páises menos desarrollados se encuentra:
- Ucrania: 33.36

En este último país vemos que hay una incidencia de más del doble en comparación con los dos países primeros. 
Esto se  debe a que en los países más desarrollados tienen una mejor calidad de vida, una estabilidad económica y financiera y eficientes servicios públicos, como es la sanidad.
Por otro lado, en países no tan desarrollados como por ejemplo Ucrania, podemos ver una inestabilidad económica agravada por los conflictos políticos.

#### 5. ¿Las tasas de cáncer de estómago han aumentado o disminuido con el tiempo?
En todos los países podemos ver que la incidencia se ha mantenido costante pero tiende ha disminuir
Esto se puede deber a mejoras en la dieta, mejoras en el estilo de vida y mejoras de sistemas de detección y tratamientos de cáncer entre otros.

#### 6. ¿El cáncer de estómago está relacionado con la cantidad de fosfatos en ríos?
Como ya hemos analizado anteriormente tanto la cantidad de fosfatos en ríos como las tasas de cáncer de estómago en Europa, han disminuido con el paso de los años.
Con estos resultados podemos pensar que existe una pequeña relación entre estos dos aspectos. Es decir, que los fosfatos que se encuentran en detergentes y fertilizantes pueden llegar a los rios dando lugar a una contaminación ambiental, y posteriormente ese agua podrá ser usado para regar en la agricultura, teniendo un impacto en la cadena alimentaria y por lo tanto en la salud humana.


